import { Roboto } from 'next/font/google';
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';

import './globals.css';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export const metadata = {
  title: {
    template: '%s | Дикий зруб',
    default: 'Дикий зруб',
  },
  // TODO: create description
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang='uk'>
      <body className={`${roboto.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
